import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '../css/home.module.css'
import styles from "../../css/[article_id].module.css"
const inter = Inter({ subsets: ['latin'] })
// import { useState } from 'react';



// icon
import { BsActivity } from "react-icons/bs";
import { BsArchiveFill } from "react-icons/bs";
import { BsCupHotFill } from "react-icons/bs";
import { BsFillBookmarkHeartFill } from "react-icons/bs";
import { BsPencilFill } from "react-icons/bs";
// icon



export default function Home() {
  // const [show, setShow] = useState(false);
  // const handleClose = () => setShow(false);
  // const handleShow = () => setShow(true);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>



{/* 側邊攔 */}{/* 側邊攔 */}{/* 側邊攔 */}{/* 側邊攔 */}
          <div className={styles.leftList}>
              <div className={styles.memberPicOut}>
                  <img className={styles.memberPic} src='/images/forum/member01.jpg'></img>
              </div>

              <div className={styles.memberItems}>
                <br></br>
                <div className={styles.name}>會員名稱</div>
                <br></br>
                <div className={styles.name}>memberNameInEng</div>
                <br></br>
                <div className={styles.nowLocationOut}>
                  <p className={styles.nowLocation}>現在在哪個論壇/總是回首頁</p>
                </div>
              </div>

            <div className={styles.iconsOut}>
              <div className={styles.icons}>
                <br></br>
                <div className={styles.icon}><BsActivity              className={styles.iconSick}/><a className={styles.iconLink} href='#'> 毛孩小毛病</a></div>
                <div className={styles.icon}><BsArchiveFill           className={styles.iconSick}/><a className={styles.iconLink} href='#'> 好用家用品</a></div>
                <div className={styles.icon}><BsCupHotFill            className={styles.iconSick}/><a className={styles.iconLink} href='#'> 時髦貓食</a></div>
                <div className={styles.icon}><BsPencilFill            className={styles.iconSick}/><a className={styles.iconLink} href='#'> 創作文章</a></div>
                <div className={styles.icon}><BsFillBookmarkHeartFill className={styles.iconSick}/><a className={styles.iconLink} href='#'> 我的收藏</a></div>
              </div>
            </div>

          </div>
{/* 側邊攔 */}{/* 側邊攔 */}{/* 側邊攔 */}{/* 側邊攔 */}





{/* 文章本人不在 */}{/* 文章本人不在 */}{/* 文章本人不在 */}

        <div className={styles.article}>
            <div className={styles.articleCard}>
              <h1>這是標題</h1>
              <div className={styles.articleCardWrAndTime}>
                <div className={styles.articleCategory}>毛起來笑</div>
                <div className={styles.articleCardWriter}>我是作者</div>
                <div className={styles.articleCardTime}>2024-01-06 23:20</div>
              </div>

              <div className={styles.articleCardContent}>
                我主管情緒陰晴不定、對人偏見很深、獨裁、自以為是心情好的時候突然對妳態度不錯，而且會給妳認但下一秒心情差的時候會在所有人面前叫你名字，用很羞辱人的表情說你的東西哪裡不對，你不能有任何的解釋，即使確定她的才是錯誤資訊，也只有她喜       歡的人才有解釋的空間，還能跟他嘻嘻哈哈（但她喜歡的也不多）她喜歡諂媚高層長官，並在長官面前罵我們，不喜歡的人她會講他的壞話在長官面前她很會包庇自己人，她的兒子也在公司上班，跟我們同一個部門，成天耍廢但位階比我們都高，績效打得比我們都高她是一個45歲左右的女主管，看起來有在保養（皺紋不多的感覺，畢竟薪水很高應該常常醫美），常常會坐在位置上用很鄙視你的眼神審閱你的東西，然後       會瘋狂吐槽你，聲音尖銳高亢，一件小事（真的很小那種）巴不得全世界知道，走進辦公室時腳也都踩得很大聲手段很賤，不會認錯，會在外部門面前羞辱自己員工以示自己的威嚴能力是有，但非常偏頗偏激，新人進來無論事情內容對或錯，她都會先狂整你，讓你不好做事，很多人剛進來都被整過缺乏安全感，只要底下有人做事很好，好到吸引到長官注意，她就會使出一連串伎倆刁難、說壞話、貶低你最近明顯被他刁難是，我拿著一份跟其他同事完全一樣規格的審稿去給他審閱卻被她劈頭罵說：「不要再用這種東西給我看，有夠難改的！應該要用XXXXX」，但前面的同事才剛剛給她一樣的格式，她卻完全沒講什麼前一陣子也是被瘋狂刁難，且每天承受她大呼小叫、走進辦公室的高跟鞋聲、陰晴不定的情緒、眼神一副你完全一無是處的鄙視都讓我好想殺了她現在每天回家都是祈禱明天她就死了，新年新希望就是她趕快死，看到她就只覺得怎麼還沒死，我死撐到現在是因為年終，但真的覺得好漫長，看到她就渾       身生厭想要她死一死有人會這樣嗎？
              </div>

              <img src='/images/forum/constent.webp'></img>



{/* 文章的按讚 分享 收藏   */}
              <div className={styles.articleCardLCS}>
                <img className={styles.like} src='/images/forum/like.svg'></img>
                <div>777</div>
                <img className={styles.chat} src='/images/forum/chat.svg'></img>
                <div>77</div>
                <img className={styles.save} src='/images/forum/save.svg'></img>
                <div>收藏</div>
              </div>
 {/* 文章的按讚 分享 收藏   */}
            

            </div>
{/* 留言們 */}{/* 留言們 */}{/* 留言們 */}{/* 留言們 */}{/* 留言們 */}



{/* 留言 */}{/* 留言 */}{/* 留言 */}{/* 留言 */}{/* 留言 */}
            <div className={styles.comment}>

              <div className={styles.commentPic}>
                <img src='/images/forum/comment01.svg'></img>
              </div>

              <div className={styles.commentRight}>
                <div className={styles.commentTime}>2024-01-06 16:44</div>
                <div className={styles.commentName}>怕滑落地</div>
                <div>選角有90分了</div>
                <div className={styles.commentLandN}>
                  <img img src='/images/forum/like.svg'></img>
                  <div className={styles.commentLikeNum}>80</div>
                </div>
              </div>

            </div>


{/* 留言 */}{/* 留言 */}{/* 留言 */}{/* 留言 */}{/* 留言 */}


{/* 留言 */}{/* 留言 */}{/* 留言 */}{/* 留言 */}{/* 留言 */}
<div className={styles.comment}>

<div className={styles.commentPic}>
  <img src='/images/forum/comment01.svg'></img>
</div>

<div className={styles.commentRight}>
  <div className={styles.commentTime}>2024-01-06 16:44</div>
  <div className={styles.commentName}>怕滑落地</div>
  <div>選角有90分了</div>
  <div className={styles.commentLandN}>
    <img img src='/images/forum/like.svg'></img>
    <div className={styles.commentLikeNum}>80</div>
  </div>
</div>

</div>


{/* 留言 */}{/* 留言 */}{/* 留言 */}{/* 留言 */}{/* 留言 */}
{/* 留言 */}{/* 留言 */}{/* 留言 */}{/* 留言 */}{/* 留言 */}
<div className={styles.comment}>

<div className={styles.commentPic}>
  <img src='/images/forum/comment01.svg'></img>
</div>

<div className={styles.commentRight}>
  <div className={styles.commentTime}>2024-01-06 16:44</div>
  <div className={styles.commentName}>怕滑落地</div>
  <div>選角有90分了</div>
  <div className={styles.commentLandN}>
    <img img src='/images/forum/like.svg'></img>
    <div className={styles.commentLikeNum}>80</div>
  </div>
</div>

</div>


{/* 留言 */}{/* 留言 */}{/* 留言 */}{/* 留言 */}{/* 留言 */}
{/* 留言 */}{/* 留言 */}{/* 留言 */}{/* 留言 */}{/* 留言 */}
<div className={styles.comment}>

<div className={styles.commentPic}>
  <img src='/images/forum/comment01.svg'></img>
</div>

<div className={styles.commentRight}>
  <div className={styles.commentTime}>2024-01-06 16:44</div>
  <div className={styles.commentName}>怕滑落地</div>
  <div>選角有90分了</div>
  <div className={styles.commentLandN}>
    <img img src='/images/forum/like.svg'></img>
    <div className={styles.commentLikeNum}>80</div>
  </div>
</div>

</div>


{/* 留言 */}{/* 留言 */}{/* 留言 */}{/* 留言 */}{/* 留言 */}




        </div>
{/* 文章本人不在 */}{/* 文章本人不在 */}{/* 文章本人不在 */}





      </main>
    </>
  )
}
