import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '../css/home.module.css'
import styles from "../../css/forum.module.css"
const inter = Inter({ subsets: ['latin'] })
// import { useState } from 'react';


//要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!

// import { Layout1 } from "@/components/Layout1";
import { useEffect, useState } from "react";
import Link from "next/link";
import { AB_LIST } from "@/components/my-const";
// import dayjs from "dayjs"; 時間的格式
import { useRouter } from "next/router";

//要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!












// icon
import { BsActivity } from "react-icons/bs";
import { BsArchiveFill } from "react-icons/bs";
import { BsCupHotFill } from "react-icons/bs";
import { BsFillBookmarkHeartFill } from "react-icons/bs";
import { BsPencilFill } from "react-icons/bs";
// icon



export default function Home() {
  // const [show, setShow] = useState(false);
  // const handleClose = () => setShow(false);
  // const handleShow = () => setShow(true);

//要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!

const [data, setData]=useState({});
const router= useRouter();
const getListData= async () =>{

let page= +router.query.page || 1;
  if(page<1) page=1;
  try {
    const r =await fetch(AB_LIST+`?page=${page}`);
    const d =await r.json();
    setData(d);
  } catch (ex) {}
};

useEffect(()=>{
  getListData();
},[router.query.page]);



//要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!要引入資料了!!!!

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>




          <div className={styles.leftList}>
              <div className={styles.memberPicOut}>
                  <img className={styles.memberPic} src='/images/forum/member01.jpg'></img>
              </div>

              <div className={styles.memberItems}>
                <br></br>
                <div className={styles.name}>會員名稱</div>
                <br></br>
                <div className={styles.name}>memberNameInEng</div>
                <br></br>
                <div className={styles.nowLocationOut}>
                  <p className={styles.nowLocation}>現在在哪個論壇/總是回首頁</p>
                </div>
              </div>

            <div className={styles.iconsOut}>
              <div className={styles.icons}>
                <br></br>
                <div className={styles.icon}><BsActivity              className={styles.iconSick}/><a className={styles.iconLink} href='#'> 毛孩小毛病</a></div>
                <div className={styles.icon}><BsArchiveFill           className={styles.iconSick}/><a className={styles.iconLink} href='#'> 好用家用品</a></div>
                <div className={styles.icon}><BsCupHotFill            className={styles.iconSick}/><a className={styles.iconLink} href='#'> 時髦貓食</a></div>
                <div className={styles.icon}><BsPencilFill            className={styles.iconSick}/><a className={styles.iconLink} href='#'> 創作文章</a></div>
                <div className={styles.icon}><BsFillBookmarkHeartFill className={styles.iconSick}/><a className={styles.iconLink} href='#'> 我的收藏</a></div>
              </div>
            </div>

          </div>


        <div className={styles.article}>
          <div className={styles.articleTitle}>
            <h4>最新</h4>&nbsp;&nbsp;&nbsp;&nbsp;<h4>熱門</h4>
          </div>
          <hr></hr>
          <div className={styles.articleWhileContents}>

{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}
            <div className={styles.articleCard}>

              <div className={styles.articleCardIcMe}>
                <img className={styles.articleCardMemberIcon} src='/images/forum/womanIcon.svg'></img>
                  &nbsp;&nbsp;
                <div className={styles.articleCardWriter}>Petnews 4小時</div>
              </div>

              <div className={styles.articleCardTitle}>快訊/網紅貓咪疑似呼麻
                <div className={styles.articleCardContent}>
                  豆漿真的要翻車了嗎 之前看他跟洋蔥似乎很要好，還吃同一包...
                </div>
              </div>
              <div className={styles.articleCardLCS}>
                <img className={styles.like} src='/images/forum/like.svg'></img>
                <div>777</div>
                <img className={styles.chat} src='/images/forum/chat.svg'></img>
                <div>77</div>
                <img className={styles.save} src='/images/forum/save.svg'></img>
                <div>收藏</div>
              </div>
             
              <img className={styles.newsPic} src='/images/forum/news.svg'></img>

            </div>
{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}


{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}
<div className={styles.articleCard}>

<div className={styles.articleCardIcMe}>
  <img className={styles.articleCardMemberIcon} src='/images/forum/womanIcon.svg'></img>
    &nbsp;&nbsp;
  <div className={styles.articleCardWriter}>Petnews 4小時</div>
</div>

<div className={styles.articleCardTitle}>快訊/網紅貓咪疑似呼麻
  <div className={styles.articleCardContent}>
    豆漿真的要翻車了嗎 之前看他跟洋蔥似乎很要好，還吃同一包...
  </div>
</div>
<div className={styles.articleCardLCS}>
  <img className={styles.like} src='/images/forum/like.svg'></img>
  <div>777</div>
  <img className={styles.chat} src='/images/forum/chat.svg'></img>
  <div>77</div>
  <img className={styles.save} src='/images/forum/save.svg'></img>
  <div>收藏</div>
</div>

<img className={styles.newsPic} src='/images/forum/news.svg'></img>

</div>
{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}
{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}
<div className={styles.articleCard}>

<div className={styles.articleCardIcMe}>
  <img className={styles.articleCardMemberIcon} src='/images/forum/womanIcon.svg'></img>
    &nbsp;&nbsp;
  <div className={styles.articleCardWriter}>Petnews 4小時</div>
</div>

<div className={styles.articleCardTitle}>快訊/網紅貓咪疑似呼麻
  <div className={styles.articleCardContent}>
    豆漿真的要翻車了嗎 之前看他跟洋蔥似乎很要好，還吃同一包...
  </div>
</div>
<div className={styles.articleCardLCS}>
  <img className={styles.like} src='/images/forum/like.svg'></img>
  <div>777</div>
  <img className={styles.chat} src='/images/forum/chat.svg'></img>
  <div>77</div>
  <img className={styles.save} src='/images/forum/save.svg'></img>
  <div>收藏</div>
</div>

<img className={styles.newsPic} src='/images/forum/news.svg'></img>

</div>
{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}
{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}
<div className={styles.articleCard}>

<div className={styles.articleCardIcMe}>
  <img className={styles.articleCardMemberIcon} src='/images/forum/womanIcon.svg'></img>
    &nbsp;&nbsp;
  <div className={styles.articleCardWriter}>Petnews 4小時</div>
</div>

<div className={styles.articleCardTitle}>快訊/網紅貓咪疑似呼麻
  <div className={styles.articleCardContent}>
    豆漿真的要翻車了嗎 之前看他跟洋蔥似乎很要好，還吃同一包...
  </div>
</div>
<div className={styles.articleCardLCS}>
  <img className={styles.like} src='/images/forum/like.svg'></img>
  <div>777</div>
  <img className={styles.chat} src='/images/forum/chat.svg'></img>
  <div>77</div>
  <img className={styles.save} src='/images/forum/save.svg'></img>
  <div>收藏</div>
</div>

<img className={styles.newsPic} src='/images/forum/news.svg'></img>

</div>
{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}
{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}
<div className={styles.articleCard}>

<div className={styles.articleCardIcMe}>
  <img className={styles.articleCardMemberIcon} src='/images/forum/womanIcon.svg'></img>
    &nbsp;&nbsp;
  <div className={styles.articleCardWriter}>Petnews 4小時</div>
</div>

<div className={styles.articleCardTitle}>快訊/網紅貓咪疑似呼麻
  <div className={styles.articleCardContent}>
    豆漿真的要翻車了嗎 之前看他跟洋蔥似乎很要好，還吃同一包...
  </div>
</div>
<div className={styles.articleCardLCS}>
  <img className={styles.like} src='/images/forum/like.svg'></img>
  <div>777</div>
  <img className={styles.chat} src='/images/forum/chat.svg'></img>
  <div>77</div>
  <img className={styles.save} src='/images/forum/save.svg'></img>
  <div>收藏</div>
</div>

<img className={styles.newsPic} src='/images/forum/news.svg'></img>

</div>
{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}

{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}
<div className={styles.articleCard}>

<div className={styles.articleCardIcMe}>
  <img className={styles.articleCardMemberIcon} src='/images/forum/womanIcon.svg'></img>
    &nbsp;&nbsp;
  <div className={styles.articleCardWriter}>Petnews 4小時</div>
</div>

<div className={styles.articleCardTitle}>快訊/網紅貓咪疑似呼麻
  <div className={styles.articleCardContent}>
    豆漿真的要翻車了嗎 之前看他跟洋蔥似乎很要好，還吃同一包...
  </div>
</div>
<div className={styles.articleCardLCS}>
  <img className={styles.like} src='/images/forum/like.svg'></img>
  <div>777</div>
  <img className={styles.chat} src='/images/forum/chat.svg'></img>
  <div>77</div>
  <img className={styles.save} src='/images/forum/save.svg'></img>
  <div>收藏</div>
</div>

<img className={styles.newsPic} src='/images/forum/news.svg'></img>

</div>
{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}{/* card */}











          </div>

        </div>

{/* 引入y4文章!!!! */}{/* 引入文章!!!! */}{/* 引入文章!!!! */}{/* 引入文章!!!! */}{/* 引入文章!!!! */}{/* 引入文章!!!! */}{/* 引入文章!!!! */}{/* 引入文章!!!! */}{/* 引入文章!!!! */}






        <div className="row">
            <pre className="col">{router.query.page}</pre>
        </div>




        <div className="row">
          <div className="col">


          <nav aria-label="Page navigation example">
            <ul className="pagination">


              {data.success && data.totalPages ? 
                  Array(11).fill(1).map((v,i)=>{
                    const p =data.page -5 +i;
                    if(p<1 || p>data.totalPages) return null;
                    return(
                            <li key={p} className={ p===data.page ?"page-item active" :"page-item"}>
                              <Link className="page-link" href={"?page=" +p }>{p}</Link>
                            </li>
                          )

                    /*
                    if(p>=1 && p<=data.totalPages){

                                            return               <li key={i} className="page-item ">
                <Link className="page-link" href="?">{i+1}</Link>
              </li>

                    } else {
                      return null;
                    }
                      */
                  })



              :null}

              {/* <li className="page-item <%= page===1 ? 'disabled' : '' %>"><a className="page-link" href="?page=1">
                <i className="fa-solid fa-angles-left"></i>
              </a></li>


              <li className="page-item <%= page===1 ? 'disabled' : '' %>"><a className="page-link" href="?page=<%= page-1 %>">
                <i className="fa-solid fa-angle-left"></i>
              </a>
            </li> */}



  {/*          
                <% for(let i=page-5; i<=page+5; i++)
                    if(i>=1 && i<=totalPages){%>
              <li className="page-item <%= i===page ? 'active' : '' %>">
                <a className="page-link" href="?<%= new URLSearchParams({...qs, page:i }).toString() %>"><%= i %></a>
              </li>
              <% }%>
*/}



              {/* <li className="page-item <%= page===totalPages ? 'disabled' : '' %>"><a className="page-link" href="?page=<%= page +1 %>">
                <i className="fa-solid fa-angle-right"></i>
              </a></li>

              <li className="page-item <%= page===totalPages ? 'disabled' : '' %>"><a className="page-link" href="?page=<%= totalPages %>">
                <i className="fa-solid fa-angles-right"></i>
              </a></li> */}


              </ul>
          </nav>






          </div>
        </div>

        <div className="row">
          <div className="col">
            <table className="table table-striped table-bordred">
              <thead>
              <tr>
                <td><i className="fa-solid fa-trash"></i></td>
                <th>編號</th>
                <th>文章編號</th>
                <th>會員編號</th>
                <th>版面</th>
                <th>標題</th>
                <th>內容</th>
                <th>發文時間</th>
                <th>更新時間</th>
                <th>
                  <i className="fa-solid fa-pen-to-square"></i>
                </th>

            </tr>
            </thead>
            <tbody>
              { data.rows && data.rows.map((i)=>{
                return(

                <tr key={i.justnumber}>
                        <td>
                          <Link href="#/" 
                          >
                            <i className="fa-solid fa-trash"></i>
                          </Link>
                        </td>
                        <td>{ i.justnumber }</td>
                        <td>{ i.article_id_post }</td>
                        <td>{ i.member_id_post }</td>
                        <td>{ i.board_category_C }</td>
                        <td>{ i.title }</td>
                        <td>{ i.content }</td>
                        {/* <td>{ dayjs(i.release_time).format('YYYY-MM-DD') }</td>  */}
                        <td>{ i.release_time}</td> 
                        <td>{ i.update_time }</td>
                        <td>
                          <Link href="/address-book/edit/">
                            <i className="fa-solid fa-pen-to-square"></i>
                          </Link>
                        </td>

                    </tr>



              );
              }) }

            </tbody>
          </table>
    </div>



</div>
{/* 引入文章!!!! */}{/* 引入文章!!!! */}{/* 引入文章!!!! */}{/* 引入文章!!!! */}{/* 引入文章!!!! */}{/* 引入文章!!!! */}{/* 引入文章!!!! */}{/* 引入文章!!!! */}{/* 引入文章!!!! */}










      </main>








    </>
  )
}
